<?php

return [
    [
        'title' => 'Appartamento nel cuore di Milano',
        'apartment_description' => 'Elegante appartamento con 3 stanze e 5 letti, situato nel centro di Milano, vicino al Duomo e ai principali servizi.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 45.4642,
        'longitude' => 9.1900,
        'user_id' => 1,
        'sponsorship_id' => 4,
        'slug' => 'appartamento-nel-cuore-di-milano'
    ],
    [
        'title' => 'Monolocale a Roma',
        'apartment_description' => 'Accogliente monolocale con 2 stanze e 3 letti, a pochi passi dal Colosseo e dai Fori Imperiali.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => false,
        'latitude' => 41.9028,
        'longitude' => 12.4964,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'monolocale-a-roma'
    ],
    [
        'title' => 'Attico panoramico a Napoli',
        'apartment_description' => 'Splendido attico con 4 stanze e 6 letti, con vista mozzafiato sul Golfo di Napoli e il Vesuvio.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 100,
        'available' => true,
        'latitude' => 40.8518,
        'longitude' => 14.2681,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'attico-panoramico-a-napoli'
    ],
    [
        'title' => 'Appartamento storico a Firenze',
        'apartment_description' => 'Affascinante appartamento con 1 stanza e 2 letti, situato nel centro storico di Firenze, vicino al Duomo.',
        'rooms' => 1,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => true,
        'latitude' => 43.7696,
        'longitude' => 11.2558,
        'user_id' => 4,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-storico-a-firenze'
    ],
    [
        'title' => 'Villa con giardino a Torino',
        'apartment_description' => 'Ampia villa con 5 stanze e 8 letti, circondata da un grande giardino, ideale per famiglie numerose.',
        'rooms' => 5,
        'beds' => 8,
        'bathroom' => 2,
        'square_mt' => 120,
        'available' => false,
        'latitude' => 45.0703,
        'longitude' => 7.6869,
        'user_id' => 5,
        'sponsorship_id' => 4,
        'slug' => 'villa-con-giardino-a-torino'
    ],
    [
        'title' => 'Bilocale moderno a Bologna',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato vicino alla stazione centrale di Bologna.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 65,
        'available' => true,
        'latitude' => 44.4949,
        'longitude' => 11.3426,
        'user_id' => 6,
        'sponsorship_id' => 3,
        'slug' => 'bilocale-moderno-a-bologna'
    ],
    [
        'title' => 'Appartamento vista lago a Como',
        'apartment_description' => 'Luminoso appartamento con 3 stanze e 4 letti, con splendida vista sul Lago di Como.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 85,
        'available' => false,
        'latitude' => 45.8105,
        'longitude' => 9.0866,
        'user_id' => 7,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-vista-lago-a-como'
    ],
    [
        'title' => 'Trilocale centrale a Venezia',
        'apartment_description' => 'Accogliente trilocale con 3 stanze e 5 letti, situato nel centro di Venezia, vicino a Piazza San Marco.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 45.4408,
        'longitude' => 12.3155,
        'user_id' => 8,
        'sponsorship_id' => 4,
        'slug' => 'trilocale-centrale-a-venezia'
    ],
    [
        'title' => 'Appartamento in centro a Verona',
        'apartment_description' => 'Appartamento con 2 stanze e 3 letti, situato nel cuore di Verona, vicino all\'Arena.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 45.4384,
        'longitude' => 10.9916,
        'user_id' => 9,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-in-centro-a-verona'
    ],
    [
        'title' => 'Loft moderno a Milano',
        'apartment_description' => 'Elegante loft con 1 stanza e 1 letto, situato nel quartiere della moda di Milano.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => false,
        'latitude' => 45.4654,
        'longitude' => 9.1866,
        'user_id' => 10,
        'sponsorship_id' => 1,
        'slug' => 'loft-moderno-a-milano'
    ],
    [
        'title' => 'Appartamento vicino alla Reggia di Caserta',
        'apartment_description' => 'Confortevole appartamento con 3 stanze e 4 letti, situato vicino alla famosa Reggia di Caserta.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 41.0759,
        'longitude' => 14.3304,
        'user_id' => 11,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-vicino-alla-reggia-di-caserta'
    ],
    [
        'title' => 'Appartamento con terrazza a Palermo',
        'apartment_description' => 'Spazioso appartamento con 4 stanze e 6 letti, dotato di una grande terrazza panoramica.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 95,
        'available' => true,
        'latitude' => 38.1157,
        'longitude' => 13.3615,
        'user_id' => 12,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-terrazza-a-palermo'
    ],
    [
        'title' => 'Monolocale economico a Torino',
        'apartment_description' => 'Monolocale conveniente con 1 stanza e 1 letto, situato vicino ai principali mezzi di trasporto.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => true,
        'latitude' => 45.0705,
        'longitude' => 7.6868,
        'user_id' => 13,
        'sponsorship_id' => 1,
        'slug' => 'monolocale-economico-a-torino'
    ],
    [
        'title' => 'Trilocale vicino al Vaticano',
        'apartment_description' => 'Trilocale con 3 stanze e 5 letti, situato a pochi passi dal Vaticano, ideale per visitare Roma.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 41.9029,
        'longitude' => 12.4534,
        'user_id' => 14,
        'sponsorship_id' => 2,
        'slug' => 'trilocale-vicino-al-vaticano'
    ],
    [
        'title' => 'Bilocale in centro a Bari',
        'apartment_description' => 'Bilocale moderno con 2 stanze e 3 letti, situato nel centro di Bari, vicino al lungomare.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 41.1171,
        'longitude' => 16.8719,
        'user_id' => 15,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-in-centro-a-bari'
    ],
    [
        'title' => 'Trilocale con vista mare a Genova',
        'apartment_description' => 'Splendido trilocale con 3 stanze e 4 letti, con vista panoramica sul mare.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 44.4056,
        'longitude' => 8.9463,
        'user_id' => 16,
        'sponsorship_id' => 1,
        'slug' => 'trilocale-con-vista-mare-a-genova'
    ],
    [
        'title' => 'Monolocale nel centro storico di Siena',
        'apartment_description' => 'Monolocale accogliente con 1 stanza e 1 letto, situato nel cuore del centro storico di Siena.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => false,
        'latitude' => 43.3188,
        'longitude' => 11.3308,
        'user_id' => 17,
        'sponsorship_id' => 3,
        'slug' => 'monolocale-nel-centro-storico-di-siena'
    ],
    [
        'title' => 'Bilocale moderno a Trento',
        'apartment_description' => 'Bilocale ristrutturato con 2 stanze e 2 letti, situato vicino al centro storico di Trento.',
        'rooms' => 2,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 46.0667,
        'longitude' => 11.1217,
        'user_id' => 18,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-moderno-a-trento'
    ],
    [
        'title' => 'Attico con terrazza a Palermo',
        'apartment_description' => 'Elegante attico con 4 stanze e 5 letti, dotato di una grande terrazza con vista panoramica.',
        'rooms' => 4,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 90,
        'available' => false,
        'latitude' => 38.1157,
        'longitude' => 13.3615,
        'user_id' => 19,
        'sponsorship_id' => 2,
        'slug' => 'attico-con-terrazza-a-palermo'
    ],
    [
        'title' => 'Appartamento in centro a Pisa',
        'apartment_description' => 'Appartamento spazioso con 3 stanze e 4 letti, situato nel cuore di Pisa, vicino alla Torre Pendente.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 43.7228,
        'longitude' => 10.4017,
        'user_id' => 20,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-in-centro-a-pisa'
    ],
    [
        'title' => 'Loft in zona Navigli a Milano',
        'apartment_description' => 'Moderno loft con 1 stanza e 2 letti, situato nel vibrante quartiere dei Navigli a Milano.',
        'rooms' => 1,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 45,
        'available' => true,
        'latitude' => 45.4523,
        'longitude' => 9.1719,
        'user_id' => 21,
        'sponsorship_id' => 4,
        'slug' => 'loft-in-zona-navigli-a-milano'
    ],
    [
        'title' => 'Appartamento con giardino a Firenze',
        'apartment_description' => 'Confortevole appartamento con 2 stanze e 3 letti, dotato di un ampio giardino privato.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => false,
        'latitude' => 43.7696,
        'longitude' => 11.2558,
        'user_id' => 22,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-giardino-a-firenze'
    ],
    [
        'title' => 'Trilocale sul lungomare di Rimini',
        'apartment_description' => 'Ampio trilocale con 3 stanze e 4 letti, situato direttamente sul lungomare di Rimini.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 44.0678,
        'longitude' => 12.5695,
        'user_id' => 23,
        'sponsorship_id' => 2,
        'slug' => 'trilocale-sul-lungomare-di-rimini'
    ],
    [
        'title' => 'Bilocale centrale a Padova',
        'apartment_description' => 'Bilocale moderno con 2 stanze e 3 letti, situato nel cuore di Padova, vicino alle principali attrazioni.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 45.4064,
        'longitude' => 11.8768,
        'user_id' => 24,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-centrale-a-padova'
    ],
    [
        'title' => 'Appartamento storico a Lecce',
        'apartment_description' => 'Affascinante appartamento con 3 stanze e 4 letti, situato in un palazzo storico nel centro di Lecce.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 40.3529,
        'longitude' => 18.1743,
        'user_id' => 25,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-storico-a-lecce'
    ],
    [
        'title' => 'Monolocale vicino al centro di Bologna',
        'apartment_description' => 'Monolocale accogliente con 1 stanza e 1 letto, situato vicino al centro di Bologna.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 40,
        'available' => true,
        'latitude' => 44.4949,
        'longitude' => 11.3426,
        'user_id' => 26,
        'sponsorship_id' => 3,
        'slug' => 'monolocale-vicino-al-centro-di-bologna'
    ],
    [
        'title' => 'Attico con vista sui colli di Torino',
        'apartment_description' => 'Spazioso attico con 3 stanze e 4 letti, con vista panoramica sui colli torinesi.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => false,
        'latitude' => 45.0703,
        'longitude' => 7.6869,
        'user_id' => 27,
        'sponsorship_id' => 2,
        'slug' => 'attico-con-vista-sui-colli-di-torino'
    ],
    [
        'title' => 'Bilocale centrale a Napoli',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel centro di Napoli, vicino alle principali attrazioni.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 40.8518,
        'longitude' => 14.2681,
        'user_id' => 28,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-centrale-a-napoli'
    ],
    [
        'title' => 'Appartamento con giardino a Perugia',
        'apartment_description' => 'Ampio appartamento con 3 stanze e 4 letti, dotato di un grande giardino privato.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 43.1121,
        'longitude' => 12.3888,
        'user_id' => 29,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-giardino-a-perugia'
    ],
    [
        'title' => 'Trilocale in centro a Trieste',
        'apartment_description' => 'Confortevole trilocale con 3 stanze e 4 letti, situato nel cuore di Trieste.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 45.6495,
        'longitude' => 13.7768,
        'user_id' => 30,
        'sponsorship_id' => 1,
        'slug' => 'trilocale-in-centro-a-trieste'
    ],
    [
        'title' => 'Monolocale economico a Cagliari',
        'apartment_description' => 'Monolocale conveniente con 1 stanza e 1 letto, situato vicino al centro di Cagliari.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => false,
        'latitude' => 39.2238,
        'longitude' => 9.1217,
        'user_id' => 31,
        'sponsorship_id' => 2,
        'slug' => 'monolocale-economico-a-cagliari'
    ],
    [
        'title' => 'Bilocale vista mare a Catania',
        'apartment_description' => 'Luminoso bilocale con 2 stanze e 3 letti, con splendida vista sul mare.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 37.5079,
        'longitude' => 15.0830,
        'user_id' => 32,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-vista-mare-a-catania'
    ],
    [
        'title' => 'Appartamento storico a Lucca',
        'apartment_description' => 'Affascinante appartamento con 2 stanze e 3 letti, situato nel centro storico di Lucca.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => false,
        'latitude' => 43.8427,
        'longitude' => 10.5027,
        'user_id' => 33,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-storico-a-lucca'
    ],
    [
        'title' => 'Trilocale vicino al mare a Ancona',
        'apartment_description' => 'Ampio trilocale con 3 stanze e 4 letti, situato vicino alla spiaggia di Ancona.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 43.6158,
        'longitude' => 13.5189,
        'user_id' => 34,
        'sponsorship_id' => 1,
        'slug' => 'trilocale-vicino-al-mare-a-ancona'
    ],
    [
        'title' => 'Bilocale centrale a Pisa',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel centro di Pisa, vicino alla Torre Pendente.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 43.7228,
        'longitude' => 10.4017,
        'user_id' => 35,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-centrale-a-pisa'
    ],
    [
        'title' => 'Appartamento con terrazza a Taranto',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 4 letti, dotato di una grande terrazza con vista mare.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 40.4667,
        'longitude' => 17.2470,
        'user_id' => 36,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-con-terrazza-a-taranto'
    ],
    [
        'title' => 'Monolocale vicino al centro di Salerno',
        'apartment_description' => 'Monolocale accogliente con 1 stanza e 1 letto, situato vicino al centro di Salerno.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => false,
        'latitude' => 40.6824,
        'longitude' => 14.7681,
        'user_id' => 37,
        'sponsorship_id' => 3,
        'slug' => 'monolocale-vicino-al-centro-di-salerno'
    ],
    [
        'title' => 'Attico con vista sui colli di Bologna',
        'apartment_description' => 'Spazioso attico con 3 stanze e 4 letti, con vista panoramica sui colli bolognesi.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 44.4949,
        'longitude' => 11.3426,
        'user_id' => 38,
        'sponsorship_id' => 1,
        'slug' => 'attico-con-vista-sui-colli-di-bologna'
    ],
    [
        'title' => 'Trilocale vicino al mare a Bari',
        'apartment_description' => 'Ampio trilocale con 3 stanze e 4 letti, situato vicino alla spiaggia di Bari.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => false,
        'latitude' => 41.1171,
        'longitude' => 16.8719,
        'user_id' => 39,
        'sponsorship_id' => 2,
        'slug' => 'trilocale-vicino-al-mare-a-bari'
    ],
    [
        'title' => 'Bilocale moderno a Cagliari',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel centro di Cagliari.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 39.2238,
        'longitude' => 9.1217,
        'user_id' => 40,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-moderno-a-cagliari'
    ],
    [
        'title' => 'Appartamento con giardino a Genova',
        'apartment_description' => 'Ampio appartamento con 3 stanze e 4 letti, dotato di un grande giardino privato.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 44.4056,
        'longitude' => 8.9463,
        'user_id' => 41,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-giardino-a-genova'
    ],
    [
        'title' => 'Monolocale economico a Lecce',
        'apartment_description' => 'Monolocale conveniente con 1 stanza e 1 letto, situato nel centro di Lecce.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => true,
        'latitude' => 40.3529,
        'longitude' => 18.1744,
        'user_id' => 42,
        'sponsorship_id' => 1,
        'slug' => 'monolocale-economico-a-lecce'
    ],
    [
        'title' => 'Bilocale in centro a Siena',
        'apartment_description' => 'Confortevole bilocale con 2 stanze e 3 letti, situato nel cuore di Siena.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => false,
        'latitude' => 43.3188,
        'longitude' => 11.3308,
        'user_id' => 43,
        'sponsorship_id' => 2,
        'slug' => 'bilocale-in-centro-a-siena'
    ],
    [
        'title' => 'Appartamento con terrazza a Parma',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 4 letti, dotato di una grande terrazza con vista sulla città.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 44.8015,
        'longitude' => 10.3280,
        'user_id' => 44,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-terrazza-a-parma'
    ],
    [
        'title' => 'Monolocale vicino al centro di Pescara',
        'apartment_description' => 'Monolocale accogliente con 1 stanza e 1 letto, situato vicino al centro di Pescara.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => true,
        'latitude' => 42.4643,
        'longitude' => 14.2142,
        'user_id' => 45,
        'sponsorship_id' => 1,
        'slug' => 'monolocale-vicino-al-centro-di-pescara'
    ],
    [
        'title' => 'Bilocale in centro a Trento',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel cuore di Trento.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => false,
        'latitude' => 46.0679,
        'longitude' => 11.1217,
        'user_id' => 46,
        'sponsorship_id' => 2,
        'slug' => 'bilocale-in-centro-a-trento'
    ],
    [
        'title' => 'Trilocale con giardino a Treviso',
        'apartment_description' => 'Confortevole trilocale con 3 stanze e 4 letti, dotato di un grande giardino privato.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 45.6669,
        'longitude' => 12.2423,
        'user_id' => 47,
        'sponsorship_id' => 3,
        'slug' => 'trilocale-con-giardino-a-treviso'
    ],
    [
        'title' => 'Bilocale in centro a Aosta',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel cuore di Aosta.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 45.7376,
        'longitude' => 7.3201,
        'user_id' => 48,
        'sponsorship_id' => 1,
        'slug' => 'bilocale-in-centro-a-aosta'
    ],
    [
        'title' => 'Appartamento vicino al mare a Rimini',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 4 letti, situato vicino alla spiaggia di Rimini.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 44.0678,
        'longitude' => 12.5695,
        'user_id' => 49,
        'sponsorship_id' => 4,
        'slug' => 'appartamento-vicino-al-mare-a-rimini'
    ],
    [
        'title' => 'Monolocale economico a Modena',
        'apartment_description' => 'Monolocale conveniente con 1 stanza e 1 letto, situato vicino al centro di Modena.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => true,
        'latitude' => 44.6471,
        'longitude' => 10.9252,
        'user_id' => 50,
        'sponsorship_id' => 3,
        'slug' => 'monolocale-economico-a-modena'
    ],
    [
        'title' => 'Bilocale vista mare a La Spezia',
        'apartment_description' => 'Luminoso bilocale con 2 stanze e 3 letti, con splendida vista sul mare.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 44.1025,
        'longitude' => 9.8241,
        'user_id' => 51,
        'sponsorship_id' => 2,
        'slug' => 'bilocale-vista-mare-a-la-spezia'
    ],
    [
        'title' => 'Appartamento con giardino a Oristano',
        'apartment_description' => 'Ampio appartamento con 3 stanze e 4 letti, dotato di un grande giardino privato.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 39.9042,
        'longitude' => 8.5917,
        'user_id' => 52,
        'sponsorship_id' => 4,
        'slug' => 'appartamento-con-giardino-a-oristano'
    ],
    [
        'title' => 'Trilocale in centro a Savona',
        'apartment_description' => 'Confortevole trilocale con 3 stanze e 4 letti, situato nel cuore di Savona.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 44.3088,
        'longitude' => 8.4812,
        'user_id' => 53,
        'sponsorship_id' => 3,
        'slug' => 'trilocale-in-centro-a-savona'
    ],
    [
        'title' => 'Monolocale economico a Benevento',
        'apartment_description' => 'Monolocale conveniente con 1 stanza e 1 letto, situato vicino al centro di Benevento.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => false,
        'latitude' => 41.1296,
        'longitude' => 14.7809,
        'user_id' => 54,
        'sponsorship_id' => 1,
        'slug' => 'monolocale-economico-a-benevento'
    ],
    [
        'title' => 'Bilocale in centro a Campobasso',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel cuore di Campobasso.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 41.5628,
        'longitude' => 14.6602,
        'user_id' => 55,
        'sponsorship_id' => 2,
        'slug' => 'bilocale-in-centro-a-campobasso'
    ],
    [
        'title' => 'Appartamento vicino al mare a Foggia',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 4 letti, situato vicino alla spiaggia di Foggia.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 41.4584,
        'longitude' => 15.5519,
        'user_id' => 56,
        'sponsorship_id' => 4,
        'slug' => 'appartamento-vicino-al-mare-a-foggia'
    ],
    [
        'title' => 'Bilocale moderno a Matera',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel centro di Matera.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 40.6689,
        'longitude' => 16.6015,
        'user_id' => 57,
        'sponsorship_id' => 1,
        'slug' => 'bilocale-moderno-a-matera'
    ],
    [
        'title' => 'Appartamento con giardino a Potenza',
        'apartment_description' => 'Ampio appartamento con 3 stanze e 4 letti, dotato di un grande giardino privato.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 40.6395,
        'longitude' => 15.8050,
        'user_id' => 58,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-con-giardino-a-potenza'
    ],
    [
        'title' => 'Trilocale in centro a Catanzaro',
        'apartment_description' => 'Confortevole trilocale con 3 stanze e 4 letti, situato nel cuore di Catanzaro.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => false,
        'latitude' => 38.9053,
        'longitude' => 16.5948,
        'user_id' => 59,
        'sponsorship_id' => 3,
        'slug' => 'trilocale-in-centro-a-catanzaro'
    ],
    [
        'title' => 'Bilocale in centro a Reggio Calabria',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato nel cuore di Reggio Calabria.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 38.1149,
        'longitude' => 15.6501,
        'user_id' => 60,
        'sponsorship_id' => 1,
        'slug' => 'bilocale-in-centro-a-reggio-calabria'
    ],
    [
        'title' => 'Appartamento in centro a Modena',
        'apartment_description' => 'Moderno appartamento con 3 stanze e 4 letti, situato nel cuore di Modena, vicino al Duomo.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 44.6471,
        'longitude' => 10.9252,
        'user_id' => 61,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-in-centro-a-modena'
    ],
    [
        'title' => 'Bilocale accogliente a Modena',
        'apartment_description' => 'Bilocale accogliente con 2 stanze e 2 letti, situato in una zona tranquilla di Modena.',
        'rooms' => 2,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => true,
        'latitude' => 44.6462,
        'longitude' => 10.9231,
        'user_id' => 62,
        'sponsorship_id' => 1,
        'slug' => 'bilocale-accogliente-a-modena'
    ],
    [
        'title' => 'Appartamento con giardino a Modena',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 5 letti, dotato di un grande giardino privato.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => false,
        'latitude' => 44.6451,
        'longitude' => 10.9272,
        'user_id' => 63,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-giardino-a-modena'
    ],
    [
        'title' => 'Monolocale centrale a Modena',
        'apartment_description' => 'Monolocale moderno con 1 stanza e 1 letto, situato nel centro di Modena, vicino ai principali servizi.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 40,
        'available' => true,
        'latitude' => 44.6470,
        'longitude' => 10.9263,
        'user_id' => 64,
        'sponsorship_id' => 4,
        'slug' => 'monolocale-centrale-a-modena'
    ],
    [
        'title' => 'Trilocale in periferia a Modena',
        'apartment_description' => 'Trilocale confortevole con 3 stanze e 4 letti, situato in una zona periferica tranquilla di Modena.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => false,
        'latitude' => 44.6493,
        'longitude' => 10.9295,
        'user_id' => 65,
        'sponsorship_id' => 2,
        'slug' => 'trilocale-in-periferia-a-modena'
    ],
    [
        'title' => 'Appartamento vicino alla stazione di Modena',
        'apartment_description' => 'Appartamento moderno con 3 stanze e 3 letti, situato vicino alla stazione centrale di Modena.',
        'rooms' => 3,
        'beds' => 3,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 44.6504,
        'longitude' => 10.9205,
        'user_id' => 66,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-vicino-alla-stazione-di-modena'
    ],
    [
        'title' => 'Attico panoramico a Modena',
        'apartment_description' => 'Splendido attico con 4 stanze e 5 letti, con vista panoramica sulla città di Modena.',
        'rooms' => 4,
        'beds' => 5,
        'bathroom' => 3,
        'square_mt' => 90,
        'available' => false,
        'latitude' => 44.6465,
        'longitude' => 10.9287,
        'user_id' => 67,
        'sponsorship_id' => 3,
        'slug' => 'attico-panoramico-a-modena'
    ],
    [
        'title' => 'Appartamento di lusso a Modena',
        'apartment_description' => 'Elegante appartamento con 3 stanze e 4 letti, arredato con finiture di lusso, situato in una zona prestigiosa di Modena.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 85,
        'available' => true,
        'latitude' => 44.6482,
        'longitude' => 10.9259,
        'user_id' => 68,
        'sponsorship_id' => 4,
        'slug' => 'appartamento-di-lusso-a-modena'
    ],
    [
        'title' => 'Appartamento economico a Modena',
        'apartment_description' => 'Conveniente appartamento con 2 stanze e 3 letti, ideale per studenti o lavoratori, situato vicino all\'università di Modena.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 44.6478,
        'longitude' => 10.9226,
        'user_id' => 69,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-economico-a-modena'
    ],
    [
        'title' => 'Appartamento con terrazza a Modena',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 4 letti, dotato di una grande terrazza con vista sulla città.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => false,
        'latitude' => 44.6459,
        'longitude' => 10.9241,
        'user_id' => 70,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-terrazza-a-modena'
    ],
    [
        'title' => 'Appartamento storico a Trastevere',
        'apartment_description' => 'Affascinante appartamento con 2 stanze e 3 letti, situato nel cuore di Trastevere, Roma.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 41.8882,
        'longitude' => 12.4663,
        'user_id' => 71,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-storico-a-trastevere'
    ],
    [
        'title' => 'Monolocale vicino a Piazza Navona',
        'apartment_description' => 'Monolocale accogliente con 1 stanza e 1 letto, a pochi passi da Piazza Navona.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 40,
        'available' => true,
        'latitude' => 41.8986,
        'longitude' => 12.4731,
        'user_id' => 72,
        'sponsorship_id' => 1,
        'slug' => 'monolocale-vicino-a-piazza-navona'
    ],
    [
        'title' => 'Appartamento vicino al Pantheon',
        'apartment_description' => 'Elegante appartamento con 3 stanze e 4 letti, situato vicino al Pantheon, Roma.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => false,
        'latitude' => 41.8992,
        'longitude' => 12.4769,
        'user_id' => 73,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-vicino-al-pantheon'
    ],
    [
        'title' => 'Trilocale moderno a Testaccio',
        'apartment_description' => 'Moderno trilocale con 3 stanze e 5 letti, situato nel quartiere di Testaccio, Roma.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 41.8762,
        'longitude' => 12.4768,
        'user_id' => 74,
        'sponsorship_id' => 4,
        'slug' => 'trilocale-moderno-a-testaccio'
    ],
    [
        'title' => 'Appartamento con vista sul Colosseo',
        'apartment_description' => 'Spazioso appartamento con 2 stanze e 3 letti, con splendida vista sul Colosseo, Roma.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 65,
        'available' => false,
        'latitude' => 41.8902,
        'longitude' => 12.4922,
        'user_id' => 75,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-con-vista-sul-colosseo'
    ],
    [
        'title' => 'Bilocale economico a San Giovanni',
        'apartment_description' => 'Bilocale economico con 2 stanze e 2 letti, situato nel quartiere San Giovanni, Roma.',
        'rooms' => 2,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => true,
        'latitude' => 41.8862,
        'longitude' => 12.5103,
        'user_id' => 76,
        'sponsorship_id' => 1,
        'slug' => 'bilocale-economico-a-san-giovanni'
    ],
    [
        'title' => 'Appartamento vicino a Villa Borghese',
        'apartment_description' => 'Elegante appartamento con 3 stanze e 4 letti, situato vicino a Villa Borghese, Roma.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => true,
        'latitude' => 41.9127,
        'longitude' => 12.4881,
        'user_id' => 77,
        'sponsorship_id' => 4,
        'slug' => 'appartamento-vicino-a-villa-borghese'
    ],
    [
        'title' => 'Loft moderno a Roma',
        'apartment_description' => 'Elegante loft con 1 stanza e 1 letto, situato nel quartiere Monti, Roma.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 45,
        'available' => false,
        'latitude' => 41.8959,
        'longitude' => 12.4948,
        'user_id' => 78,
        'sponsorship_id' => 3,
        'slug' => 'loft-moderno-a-roma'
    ],
    [
        'title' => 'Appartamento con terrazza a Roma',
        'apartment_description' => 'Spazioso appartamento con 3 stanze e 4 letti, dotato di una grande terrazza panoramica.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 85,
        'available' => true,
        'latitude' => 41.9006,
        'longitude' => 12.4963,
        'user_id' => 79,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-con-terrazza-a-roma'
    ],
    [
        'title' => 'Bilocale vicino a Piazza di Spagna',
        'apartment_description' => 'Confortevole bilocale con 2 stanze e 3 letti, situato a pochi passi da Piazza di Spagna, Roma.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => false,
        'latitude' => 41.9057,
        'longitude' => 12.4823,
        'user_id' => 80,
        'sponsorship_id' => 4,
        'slug' => 'bilocale-vicino-a-piazza-di-spagna'
    ],
];
