<?php

return [
    [
        'title' => 'Appartamento nel cuore di Milano',
        'apartment_description' => 'Elegante appartamento con 3 stanze e 5 letti, situato nel centro di Milano, vicino al Duomo e ai principali servizi.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 45.4642,
        'longitude' => 9.1900,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-nel-cuore-di-milano',
    ],
    [
        'title' => 'Monolocale a Roma',
        'apartment_description' => 'Accogliente monolocale con 2 stanze e 3 letti, a pochi passi dal Colosseo e dai Fori Imperiali.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => false,
        'latitude' => 41.9028,
        'longitude' => 12.4964,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'monolocale-a-roma',
    ],
    [
        'title' => 'Attico panoramico a Napoli',
        'apartment_description' => 'Splendido attico con 4 stanze e 6 letti, con vista mozzafiato sul Golfo di Napoli e il Vesuvio.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 100,
        'available' => true,
        'latitude' => 40.8518,
        'longitude' => 14.2681,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'attico-panoramico-a-napoli',
    ],
    [
        'title' => 'Villetta sul lago di Como',
        'apartment_description' => 'Accogliente villetta con vista mozzafiato sul lago di Como, perfetta per una vacanza rilassante in famiglia.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 45.9642,
        'longitude' => 9.2350,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'villetta-sul-lago-di-como',
    ],
    [
        'title' => 'Casa vacanze in Toscana',
        'apartment_description' => 'Tipica casa toscana immersa nelle colline, ideale per scoprire la bellezza dei borghi medievali e dei vigneti circostanti.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 43.3188,
        'longitude' => 11.3304,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'casa-vacanze-in-toscana',
    ],
    [
        'title' => 'Appartamento moderno a Firenze',
        'apartment_description' => 'Moderno appartamento nel cuore di Firenze, con vista sulla cattedrale di Santa Maria del Fiore e comodo accesso ai musei principali.',
        'rooms' => 1,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 43.7696,
        'longitude' => 11.2558,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-moderno-a-firenze',
    ],
    [
        'title' => 'Chalet in montagna a Cortina',
        'apartment_description' => 'Chalet elegante e accogliente nelle Dolomiti, ideale per gli amanti dello sci e delle escursioni in montagna.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 2,
        'square_mt' => 90,
        'available' => true,
        'latitude' => 46.5386,
        'longitude' => 12.1350,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'chalet-in-montagna-a-cortina',
    ],
    [
        'title' => 'Trullo tradizionale in Puglia',
        'apartment_description' => 'Autentico trullo pugliese con 2 stanze e 3 letti, circondato da ulivi secolari e a breve distanza dalle spiagge di Ostuni.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 65,
        'available' => false,
        'latitude' => 40.7828,
        'longitude' => 17.2350,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'trullo-tradizionale-in-puglia',
    ],
    [
        'title' => 'Appartamento storico a Verona',
        'apartment_description' => 'Affascinante appartamento nel centro storico di Verona, a due passi dall\'Arena e dalle principali attrazioni della città.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 45.4384,
        'longitude' => 10.9916,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-storico-a-verona',
    ],
    [
        'title' => 'Casa sul mare in Sardegna',
        'apartment_description' => 'Casa spaziosa con vista mozzafiato sul mare cristallino della Sardegna, ideale per una vacanza di relax e sole.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 39.2150,
        'longitude' => 9.1212,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'casa-sul-mare-in-sardegna',
    ],
    [
        'title' => 'Appartamento panoramico a Bergamo',
        'apartment_description' => 'Appartamento con vista panoramica sulla Città Alta di Bergamo, situato in una zona tranquilla ma ben collegata con il centro città.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 65,
        'available' => false,
        'latitude' => 45.7044,
        'longitude' => 9.6606,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-panoramico-a-bergamo',
    ],
    [
        'title' => 'Villa con piscina in Toscana',
        'apartment_description' => 'Villa di lusso con piscina privata e ampio giardino, immersa nelle colline toscane tra vigneti e oliveti.',
        'rooms' => 5,
        'beds' => 8,
        'bathroom' => 3,
        'square_mt' => 120,
        'available' => true,
        'latitude' => 43.3188,
        'longitude' => 11.3304,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'villa-con-piscina-in-toscana',
    ],
    [
        'title' => 'Appartamento con terrazza a Genova',
        'apartment_description' => 'Appartamento con terrazza panoramica sul porto di Genova, ideale per godersi le serate estive con una vista mozzafiato.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 44.4056,
        'longitude' => 8.9463,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-con-terrazza-a-genova',
    ],
    [
        'title' => 'Chalet di montagna a Courmayeur',
        'apartment_description' => 'Chalet di lusso a Courmayeur con vista sulle cime delle Alpi, perfetto per una vacanza tra sport invernali e relax.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 100,
        'available' => true,
        'latitude' => 45.7936,
        'longitude' => 6.9681,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'chalet-di-montagna-a-courmayeur',
    ],
    [
        'title' => 'Appartamento moderno a Bologna',
        'apartment_description' => 'Moderno appartamento nel cuore di Bologna, a pochi passi dalle Due Torri e dai principali musei della città.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 44.4949,
        'longitude' => 11.3426,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-moderno-a-bologna',
    ],
    [
        'title' => 'Villetta con giardino a Lucca',
        'apartment_description' => 'Villetta con giardino privato nel centro storico di Lucca, ideale per una vacanza immersi nella storia e nella cultura della Toscana.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 85,
        'available' => true,
        'latitude' => 43.8420,
        'longitude' => 10.5027,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'villetta-con-giardino-a-lucca',
    ],
    [
        'title' => 'Casa rurale in Umbria',
        'apartment_description' => 'Casa rurale immersa nel verde dell\'Umbria, ideale per una vacanza relax e natura tra le colline e i borghi medievali.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 42.9380,
        'longitude' => 12.6216,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'casa-rurale-in-umbria',
    ],
    [
        'title' => 'Appartamento sulla spiaggia a Rimini',
        'apartment_description' => 'Appartamento sulla spiaggia di Rimini, con accesso diretto alla sabbia dorata e vista sul mare Adriatico.',
        'rooms' => 1,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => false,
        'latitude' => 44.0678,
        'longitude' => 12.5683,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-sulla-spiaggia-a-rimini',
    ],
    [
        'title' => 'Villa con vista sulle Cinque Terre',
        'apartment_description' => 'Villa con vista mozzafiato sulle Cinque Terre, immersa nella natura e ideale per una vacanza di relax e trekking.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 95,
        'available' => true,
        'latitude' => 44.1026,
        'longitude' => 9.7373,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'villa-con-vista-sulle-cinque-terre',
    ],
    [
        'title' => 'Appartamento con terrazza a Palermo',
        'apartment_description' => 'Appartamento con terrazza panoramica sul centro storico di Palermo, ideale per scoprire l\'arte e la cultura della città.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 38.1157,
        'longitude' => 13.3615,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-con-terrazza-a-palermo',
    ],
    [
        'title' => 'Chalet sulle Alpi a Livigno',
        'apartment_description' => 'Chalet moderno e accogliente a Livigno, circondato dalle montagne delle Alpi, perfetto per una vacanza sciistica in inverno e escursioni in estate.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 85,
        'available' => true,
        'latitude' => 46.5400,
        'longitude' => 10.1718,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'chalet-sulle-alpi-a-livigno',
    ],
    [
        'title' => 'Appartamento storico a Venezia',
        'apartment_description' => 'Affascinante appartamento nel centro storico di Venezia, a pochi passi da Piazza San Marco e dai canali veneziani.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => false,
        'latitude' => 45.4347,
        'longitude' => 12.3383,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-storico-a-venezia',
    ],
    [
        'title' => 'Casa vacanze con piscina a Sicilia',
        'apartment_description' => 'Casa vacanze con piscina privata in Sicilia, ideale per una vacanza di sole, mare e cultura tra le bellezze dell\'isola.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 100,
        'available' => true,
        'latitude' => 37.5994,
        'longitude' => 14.0154,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'casa-vacanze-con-piscina-a-sicilia',
    ],
    [
        'title' => 'Appartamento con vista su Firenze',
        'apartment_description' => 'Appartamento con vista mozzafiato su Firenze, situato sulle colline toscane e perfetto per una vacanza romantica e culturale.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 43.7669,
        'longitude' => 11.2588,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-vista-su-firenze',
    ],
];
