<?php

return [
    [
        'title' => 'Appartamento nel cuore di Milano',
        'apartment_description' => 'Elegante appartamento con 3 stanze e 5 letti, situato nel centro di Milano, vicino al Duomo e ai principali servizi.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 75,
        'available' => true,
        'latitude' => 45.4642,
        'longitude' => 9.1900,
        'user_id' => 1,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-nel-cuore-di-milano'
    ],
    [
        'title' => 'Monolocale a Roma',
        'apartment_description' => 'Accogliente monolocale con 2 stanze e 3 letti, a pochi passi dal Colosseo e dai Fori Imperiali.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => false,
        'latitude' => 41.9028,
        'longitude' => 12.4964,
        'user_id' => 2,
        'sponsorship_id' => 2,
        'slug' => 'monolocale-a-roma'
    ],
    [
        'title' => 'Attico panoramico a Napoli',
        'apartment_description' => 'Splendido attico con 4 stanze e 6 letti, con vista mozzafiato sul Golfo di Napoli e il Vesuvio.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 100,
        'available' => true,
        'latitude' => 40.8518,
        'longitude' => 14.2681,
        'user_id' => 3,
        'sponsorship_id' => 3,
        'slug' => 'attico-panoramico-a-napoli'
    ],
    [
        'title' => 'Appartamento storico a Firenze',
        'apartment_description' => 'Affascinante appartamento con 1 stanza e 2 letti, situato nel centro storico di Firenze, vicino al Duomo.',
        'rooms' => 1,
        'beds' => 2,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => true,
        'latitude' => 43.7696,
        'longitude' => 11.2558,
        'user_id' => 4,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-storico-a-firenze'
    ],
    [
        'title' => 'Villa con giardino a Torino',
        'apartment_description' => 'Ampia villa con 5 stanze e 8 letti, circondata da un grande giardino, ideale per famiglie numerose.',
        'rooms' => 5,
        'beds' => 8,
        'bathroom' => 2,
        'square_mt' => 120,
        'available' => false,
        'latitude' => 45.0703,
        'longitude' => 7.6869,
        'user_id' => 5,
        'sponsorship_id' => 2,
        'slug' => 'villa-con-giardino-a-torino'
    ],
    [
        'title' => 'Bilocale moderno a Bologna',
        'apartment_description' => 'Moderno bilocale con 2 stanze e 3 letti, situato vicino alla stazione centrale di Bologna.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 65,
        'available' => true,
        'latitude' => 44.4949,
        'longitude' => 11.3426,
        'user_id' => 6,
        'sponsorship_id' => 3,
        'slug' => 'bilocale-moderno-a-bologna'
    ],
    [
        'title' => 'Appartamento vista lago a Como',
        'apartment_description' => 'Luminoso appartamento con 3 stanze e 4 letti, con splendida vista sul Lago di Como.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 85,
        'available' => false,
        'latitude' => 45.8105,
        'longitude' => 9.0866,
        'user_id' => 7,
        'sponsorship_id' => 1,
        'slug' => 'appartamento-vista-lago-a-como'
    ],
    [
        'title' => 'Trilocale centrale a Venezia',
        'apartment_description' => 'Accogliente trilocale con 3 stanze e 5 letti, situato nel centro di Venezia, vicino a Piazza San Marco.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 80,
        'available' => true,
        'latitude' => 45.4408,
        'longitude' => 12.3155,
        'user_id' => 8,
        'sponsorship_id' => 2,
        'slug' => 'trilocale-centrale-a-venezia'
    ],
    [
        'title' => 'Appartamento in centro a Verona',
        'apartment_description' => 'Appartamento con 2 stanze e 3 letti, situato nel cuore di Verona, vicino all\'Arena.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 60,
        'available' => true,
        'latitude' => 45.4384,
        'longitude' => 10.9916,
        'user_id' => 9,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-in-centro-a-verona'
    ],
    [
        'title' => 'Loft moderno a Milano',
        'apartment_description' => 'Elegante loft con 1 stanza e 1 letto, situato nel quartiere della moda di Milano.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 50,
        'available' => false,
        'latitude' => 45.4654,
        'longitude' => 9.1866,
        'user_id' => 10,
        'sponsorship_id' => 1,
        'slug' => 'loft-moderno-a-milano'
    ],
    [
        'title' => 'Appartamento vicino alla Reggia di Caserta',
        'apartment_description' => 'Confortevole appartamento con 3 stanze e 4 letti, situato vicino alla famosa Reggia di Caserta.',
        'rooms' => 3,
        'beds' => 4,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 41.0759,
        'longitude' => 14.3304,
        'user_id' => 11,
        'sponsorship_id' => 2,
        'slug' => 'appartamento-vicino-alla-reggia-di-caserta'
    ],
    [
        'title' => 'Appartamento con terrazza a Palermo',
        'apartment_description' => 'Spazioso appartamento con 4 stanze e 6 letti, dotato di una grande terrazza panoramica.',
        'rooms' => 4,
        'beds' => 6,
        'bathroom' => 3,
        'square_mt' => 95,
        'available' => true,
        'latitude' => 38.1157,
        'longitude' => 13.3615,
        'user_id' => 12,
        'sponsorship_id' => 3,
        'slug' => 'appartamento-con-terrazza-a-palermo'
    ],
    [
        'title' => 'Monolocale economico a Torino',
        'apartment_description' => 'Monolocale conveniente con 1 stanza e 1 letto, situato vicino ai principali mezzi di trasporto.',
        'rooms' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'square_mt' => 35,
        'available' => true,
        'latitude' => 45.0705,
        'longitude' => 7.6868,
        'user_id' => 13,
        'sponsorship_id' => 1,
        'slug' => 'monolocale-economico-a-torino'
    ],
    [
        'title' => 'Trilocale vicino al Vaticano',
        'apartment_description' => 'Trilocale con 3 stanze e 5 letti, situato a pochi passi dal Vaticano, ideale per visitare Roma.',
        'rooms' => 3,
        'beds' => 5,
        'bathroom' => 2,
        'square_mt' => 70,
        'available' => false,
        'latitude' => 41.9029,
        'longitude' => 12.4534,
        'user_id' => 14,
        'sponsorship_id' => 2,
        'slug' => 'trilocale-vicino-al-vaticano'
    ],
    [
        'title' => 'Bilocale in centro a Bari',
        'apartment_description' => 'Bilocale moderno con 2 stanze e 3 letti, situato nel centro di Bari, vicino al lungomare.',
        'rooms' => 2,
        'beds' => 3,
        'bathroom' => 1,
        'square_mt' => 55,
        'available' => true,
        'latitude' => 41.1171,
        'longitude' => 16.8719,
        'user_id' => 15,
        'sponsorship_id' => 3,
        'slug' => 'bilocale-in-centro-a-bari'
    ]
];
