<?php

return [
    [
        'name' => 'Marco',
        'lastname' => 'Rossi',
        'email' => 'marco.rossi@example.com',
        'password' => 'password1',
        'birth_date' => '1990-05-15',
    ],
    [
        'name' => 'Giulia',
        'lastname' => 'Ferrari',
        'email' => 'giulia.ferrari@example.com',
        'password' => 'password2',
        'birth_date' => '1985-08-22',
    ],
    [
        'name' => 'Luca',
        'lastname' => 'Russo',
        'email' => 'luca.russo@example.com',
        'password' => 'password3',
        'birth_date' => '1982-03-10',
    ],
    [
        'name' => 'Chiara',
        'lastname' => 'Bianchi',
        'email' => 'chiara.bianchi@example.com',
        'password' => 'password4',
        'birth_date' => '1995-11-27',
    ],
    [
        'name' => 'Matteo',
        'lastname' => 'Romano',
        'email' => 'matteo.romano@example.com',
        'password' => 'password5',
        'birth_date' => '1988-07-18',
    ],
    [
        'name' => 'Valentina',
        'lastname' => 'Colombo',
        'email' => 'valentina.colombo@example.com',
        'password' => 'password6',
        'birth_date' => '1993-01-05',
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Marini',
        'email' => 'alessandro.marini@example.com',
        'password' => 'password7',
        'birth_date' => '1984-09-30',
    ],
    [
        'name' => 'Sara',
        'lastname' => 'Conti',
        'email' => 'sara.conti@example.com',
        'password' => 'password8',
        'birth_date' => '1991-06-14',
    ],
    [
        'name' => 'Davide',
        'lastname' => 'Barbieri',
        'email' => 'davide.barbieri@example.com',
        'password' => 'password9',
        'birth_date' => '1987-04-03',
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Moretti',
        'email' => 'elisa.moretti@example.com',
        'password' => 'password10',
        'birth_date' => '1996-02-19',
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Galli',
        'email' => 'paolo.galli@example.com',
        'password' => 'password11',
        'birth_date' => '1983-12-08',
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Marchetti',
        'email' => 'anna.marchetti@example.com',
        'password' => 'password12',
        'birth_date' => '1994-10-25',
    ],
    [
        'name' => 'Giovanni',
        'lastname' => 'Silvestri',
        'email' => 'giovanni.silvestri@example.com',
        'password' => 'password13',
        'birth_date' => '1989-08-07',
    ],
    [
        'name' => 'Laura',
        'lastname' => 'Ferrara',
        'email' => 'laura.ferrara@example.com',
        'password' => 'password14',
        'birth_date' => '1992-05-20',
    ],
    [
        'name' => 'Federico',
        'lastname' => 'Martini',
        'email' => 'federico.martini@example.com',
        'password' => 'password15',
        'birth_date' => '1986-11-12',
    ],
];
